---
development:
  API_URL:        http://localhost:3000/api/v1
  APP_URL:        http://localhost:9292
  GH_OAUTH_URL:   https://github.com/login/oauth/authorize
  GH_TOKEN_URL:   https://github.com/login/oauth/access_token

test:
  API_URL:        http://localhost:3000/api/v1
  APP_URL:        http://localhost:9292

production:
  API_URL:        https://credent-api.herokuapp.com/api/v1
  APP_URL:        https://credent.herokuapp.com
