---
development:
  SESSION_SECRET: ZnAgEIWdvHCjn3EiO1qL9XdCS8EUUM6Iy8SmokttsMt4ZjA5H0/NbEwlTcJvFXROZ11et2k53N7bXpWqvwqUFQ==
  REDIS_URL:      redis://h:p578e8dd17a34516ab3561f5982f42fdad62b77058865cef21cfc513248c958c3@ec2-52-4-102-90.compute-1.amazonaws.com:17279
  MSG_KEY:        WAJW2A2VUU2dRIFzORd/EOw1RohLsXJEBXYGiBNN75Q=
test:
  SESSION_SECRET: ZnAgEIWdvHCjn3EiO1qL9XdCS8EUUM6Iy8SmokttsMt4ZjA5H0/NbEwlTcJvFXROZ11et2k53N7bXpWqvwqUFQ==
  REDIS_URL:      redis://h:p578e8dd17a34516ab3561f5982f42fdad62b77058865cef21cfc513248c958c3@ec2-52-4-102-90.compute-1.amazonaws.com:17279
  MSG_KEY:        WAJW2A2VUU2dRIFzORd/EOw1RohLsXJEBXYGiBNN75Q=
production:
  SESSION_SECRET: It6bt4OMbfvVfZrktJB0FI7xYjHN6VL3Hr9CsI3fJVP83IeGlxwWvRNsOQWq+1xn++F5sny3YKcnmVsU9MiyNA==
  REDIS_URL:      redis://h:p578e8dd17a34516ab3561f5982f42fdad62b77058865cef21cfc513248c958c3@ec2-52-4-102-90.compute-1.amazonaws.com:17279
  MSG_KEY:        vtZaelnOCEMK6KVvvm/fvSDir+m6q6uBUlXOUVcbHS4=
