# Use as template for secrets.yml
---
development:
  SESSION_SECRET:   <generate with `rake generate:session_secret`>
  MSG_KEY:          <generate with `rake generate:msg_key`>
  REDIS_URL:        <Provision a Redis URL>
  GH_CLIENT_ID:     <Get Github OAuth Client ID>
  GH_CLIENT_SECRET: <Get Github OAuth Client Secret>